stages:

  download_data:
    cmd: python src/data/download_dataset.py
    deps:
    - src/data/download_dataset.py
    outs:
    - data/external
    params:
    - data_folder_id
    - data_folder

  tokenize_data:
    cmd: poetry run python -m lib_ml.preprocessing
    deps:
    - pyproject.toml
    outs:
    - artifacts/tokenized
    params:
    - tokenized_folder
    - data_folder

  train_model:
    cmd: python src/models/train_model.py
    deps:
    - src/models/train_model.py
    outs:
    - artifacts/trained
    params:
    - epochs
    - batch_size
    - categories
    - loss_function
    - optimizer
    - tokenized_folder
    - trained_folder

  predict_model:
    cmd: python src/models/predict_model.py
    deps:
    - src/models/predict_model.py
    outs:
    - artifacts/predicted
    params:
    - predicted_folder
    - trained_folder
    - tokenized_folder

metrics:
  - artifacts/predicted/metrics.json
