name: ML Model Tests - Data and Feature Testing

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Download dataset
      run: |
        pip install gdown dvc
        python download_data.py

    - name: Run tests
      run: |
        poetry run pytest tests/
