name: ML Model Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Download dataset
      run: |
         poetry run python src/data/download_dataset.py

    - name: Run tests
      run: |
        poetry run pytest -s tests/ --json-report --json-report-file=report.json

    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: report.json

    - name: Generate badge
      run: |
        poetry run python report_tests.py

    - name: Upload badge
      uses: actions/upload-artifact@v2
      with:
        name: test-badge
        path: badge.svg

